# Generated by Django 4.1.5 on 2023-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(default=None, max_length=254)),
                ('usn', models.CharField(default=None, max_length=20)),
                ('print', models.BooleanField(default=False)),
                ('bindings', models.BooleanField(default=False)),
                ('print_type', models.CharField(choices=[('B & W', 'Black & White'), ('Colour', 'Colour')], default=None, max_length=128)),
                ('file', models.FileField(default=None, upload_to='')),
                ('total_pages', models.IntegerField(default=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('print_status', models.TextField(default=False)),
                ('amount', models.IntegerField(default=None)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
    ]
